### ISSUE TITLE
Advanced tool report: status variable has different labels

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#26]
Please change the status variable so the labels/responses are the same everywhere. At this point, I would like to change the values to these to be clearer for the user:
- Not applicable
- Planned expenditure
- Budgeted expenditure
- Historical expenditure
- Mixed expenditure
- Don't know

**Comment by mhig** [comment]
What are the French translations of these?

**Comment by mhig** [comment]
Merge with #25 

The status variable of a report does not show up correctly in the dashboard when assigned to the report.

To reproduce, go to this shared report (all empty except the status), save it, and check the dashboard:
http://washcost.herokuapp.com/en/report/539ee3dd27795ac327000026

image

In the dashboard it is not reported as existing:

image

I would suggest to use a single variable instead of having two separate ones.

**Comment by nickdickinson** [comment]
I'm working on the translations now.

**Comment by nickdickinson** [comment]
Not applicable --> Non applicable
Planned expenditure --> Dépense prévisionnelle
Budgeted expenditure --> Dépenses budgetées
Historical expenditure --> Dépenses historiques
Mixed types of expenditure --> Dépenses diverses
Don't know --> Ne sais pas
