### ISSUE TITLE
Advanced: Dashboard - CapEx per person calculation error

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#42]
I tested the calculation of "CapEx per person" in the following report:

http://www.ircwash.org/washcost?id=53a946564982c46f2600001b

This report is for a system in the USA - with US$ in 2011 - therefore there should be no adjustments necessary for comparison on the dashboard.

The example inputs were the following:

Total CapEx Hardware (sum of CapEx Hrd for the 3 inputted systems) = 260,000
Total CapEx Software (sum of CapEx sft for the 3 inputted systems) =6,000
Total CapEx = 266,000

Total actual populations served =  28,000

Therefore Total CapEx / Total Actual pop = US$9.50

However the reported figure on the dashboard is: US$ 4.10

**Comment by nickdickinson** [comment]
Corrected share link:
http://washcost.herokuapp.com/en/report/53a946564982c46f2600001b

On 24 June 2014 11:43, peterburr notifications@github.com wrote:

> I tested the calculation of "CapEx per person" in the following report:
> 
> http://www.ircwash.org/washcost?id=53a946564982c46f2600001b
> 
> This report is for a system in the USA - with US$ in 2011 - therefore
> there should be no adjustments necessary for comparison on the dashboard.
> 
> The example inputs were the following:
> 
> Total CapEx Hardware (sum of CapEx Hrd for the 3 inputted systems) =
> 260,000
> Total CapEx Software (sum of CapEx sft for the 3 inputted systems) =6,000
> Total CapEx = 266,000
> 
> Total actual populations served = 28,000
> 
> Therefore Total CapEx / Total Actual pop = US$9.50
> 
> However the reported figure on the dashboard is: US$ 4.10
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ircwash/WASHCost-tool/issues/42.

## 

Nicolas Dickinson
Senior Programme Officer
Monitoring and IT Expert

Postal address:
P.O. Box 82327
2508 EH The Hague
The Netherlands

http://www.ircwash.org

T: +31 70 304 4038
M: +31 649875488
Twitter: @waternote

http://www.twitter.com/waternote

## 

http://www.irc.nl/page/73684

**Comment by nickdickinson** [comment]
I've been able to replicate this exactly with a single technology so the
problem is not how it is summed over technologies:
http://washcost.herokuapp.com/en/report/53a950d44982c46f26000022

I've done several more tests and the total population changes and the
changes to cost seem to change the total value proportionally in the right
direction (by the same factor as in the change of inputs). So it seems that
the problem is in final_usd_2011(q, value) most likely. The conversion to
USD 2011. The thing is that this example is USD 2011 so there should be no
conversion at all if the look up tables are working correctly.

Nick

On 24 June 2014 11:43, peterburr notifications@github.com wrote:

> I tested the calculation of "CapEx per person" in the following report:
> 
> http://www.ircwash.org/washcost?id=53a946564982c46f2600001b
> 
> This report is for a system in the USA - with US$ in 2011 - therefore
> there should be no adjustments necessary for comparison on the dashboard.
> 
> The example inputs were the following:
> 
> Total CapEx Hardware (sum of CapEx Hrd for the 3 inputted systems) =
> 260,000
> Total CapEx Software (sum of CapEx sft for the 3 inputted systems) =6,000
> Total CapEx = 266,000
> 
> Total actual populations served = 28,000
> 
> Therefore Total CapEx / Total Actual pop = US$9.50
> 
> However the reported figure on the dashboard is: US$ 4.10
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ircwash/WASHCost-tool/issues/42.

## 

Nicolas Dickinson
Senior Programme Officer
Monitoring and IT Expert

Postal address:
P.O. Box 82327
2508 EH The Hague
The Netherlands

http://www.ircwash.org

T: +31 70 304 4038
M: +31 649875488
Twitter: @waternote

http://www.twitter.com/waternote

## 

http://www.irc.nl/page/73684

**Comment by mhig** [comment]
Capital expenditure per person and recurrent expenditure per person per year base calculations are correct and have been validated by Nick.

The FX and Inflator/Deflator is now outstanding issue
